config/routes.rb
Rails.application.routes.draw do
  root 'home#directory'

  get 'map', to: 'home#map', as: :map
  get 'dashboard', to: 'home#dashboard', as: :dashboard

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :events, only: [:index]
      get 'recent_countries', to: 'events#recent_countries', as: :recent_countries
      get 'cities_by_country', to: 'events#cities_by_country', as: :cities_by_country
      get 'events_by_country', to: 'events#events_by_country', as: :events_by_country
      get 'events_by_city', to: 'events#events_by_city', as: :events_by_city
    end
  end

  resources :events do
    post 'delete_venue_from', on: :member
  end

  resources :venues, only: [:index, :show, :edit, :update] do
    post 'delete_event_from', on: :member
  end

  get 'sign_up', to: 'users#new', as: :sign_up
  resources :users

  get 'sign_in', to: 'sessions#new', as: :sign_in
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy', as: :sign_out
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :venues, :uniq => true

  scope :recent, -> { order(updated_at: :desc) }
  scope :names, -> { pluck(:name).uniq }

  # get the city in which the most venues are found
  def primary_city
    mode(self.venues.cities)
  end

  private
    def mode(array)
      freq = array.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
      array.max_by { |v| freq[v] }
    end
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

end

app/models/venue.rb
class Venue < ApplicationRecord
  has_and_belongs_to_many :events, :uniq => true

  scope :cities, -> { pluck(:city).uniq }
  scope :cities_in_country, -> (country) { where(country: country).pluck(:city).uniq }
  scope :countries, -> { pluck(:country).uniq }
  scope :names, -> { pluck(:name).uniq }

  scope :coordinates, -> { pluck(:latitude, :longitude).uniq }

  geocoded_by :given_address do |venue, results|
    if geo = results.first
      venue.latitude = geo.latitude
      venue.longitude = geo.longitude
      venue.street_address = geo.street_address
      venue.city = geo.city
      venue.state = geo.state
      venue.country = geo.country
      venue.formatted_address = geo.formatted_address
    end
  end

  after_validation :geocode, :if => lambda{ |obj| obj.given_address_changed? }

  def self.cities_by_country
    citiesByCountry = Hash.new()
    self.countries.each do |c|
      citiesByCountry[c] = Event.recent.joins(:venues).where(venues: { country: c }).pluck('venues.city').uniq
    end
    citiesByCountry
  end

end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < ApplicationController
      def index
        @events = Event.all
      end

      def recent_countries
        @countries = Event.countries
      end

      def cities_by_country
        @country = params[:country] || ""
        @cities = Event.cities_in_country(@country)
      end

      def recent_events
        @events = Event.recent
      end

      def events_by_country
        @country = params[:country] || ""
        @events = Event.where(country: @country)
      end

      def events_by_city
        @city = params[:city] || ""
        # @state = params[:state] || ""
        @events = Event.where(city: @city)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to sign_in_path unless current_user
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authorize

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    @event.save
    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event successfully updated"
      redirect_to @event
    else
      flash[:error] = "Event was not updated"
      render 'edit'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event successfully removed"
    redirect_to events_path
  end

  def delete_venue_from
    @event = Event.find(params[:id])
    venue = @event.venues.find(params[:venue_id])

    if venue
      @event.venues.delete(venue)
    end

    redirect_to @event
  end

  private
    def event_params
      params.require(:event).permit(:name, :presenter, :start_date, :end_date,
                                    :description, :website, :facebook,
                                    :instagram, :twitter, :youtube)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authorize, only: [:dashboard]

  def dashboard
  end

  def directory
    @events = Event.recent.includes(:venues)
    @recent_countries = Venue.countries
    gon.jbuilder template: 'app/views/api/v1/events/index.json.jbuilder', as: :events

    gon.citiesByCountry = Venue.cities_by_country
  end

  def map
    @events = Event.recent.includes(:venues)
    gon.jbuilder template: 'app/views/api/v1/events/index.json.jbuilder', as: :events
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      redirect_to sign_in_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to sign_in_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      redirect_to signup_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  before_action :authorize

  def index
    @venues = Venue.all
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def update
    @venue = Venue.find(params[:id])
    if @venue.update_attributes(venue_params)
      flash[:success] = "Venue successfully updated"
      redirect_to @venue
    else
      flash[:error] = "Venue was not updated"
      render 'edit'
    end
  end

  def delete_event_from
    @venue = Venue.find(params[:id])
    event = @venue.events.find(params[:event_id])

    if event
      @venue.events.delete(event)
    end

    redirect_to @venue
  end

  private
    def venue_params
      params.require(:venue).permit(:name, :latitude, :longitude, :given_address,
                                    :formatted_address, :street_address, :city,
                                    :state, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  # return username from link (assuming that username is at end of link)
  def username(link)
    link.split('/').last
  end
end

app/helpers/link_helper.rb
module LinkHelper
  def google_maps_url
    "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_maps_api_key}&callback=initMapModus"
  end

  def instagram_url(username)
    "https://www.instagram.com/" + username
  end

  def twitter_url(username)
    "https://www.twitter.com/" + username
  end
end

app/helpers/list_helper.rb
module ListHelper
  # output comma-separated list of cities for a group of venues
  def comma_separated_list(array)
    array.join(", ")
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
  def coordinates(venue)
    "#{venue.latitude}, #{venue.longitude}"
  end
end

app/views/events/_form.html.slim
p
  = f.label :name, class: "required"
  br
  = f.text_field :name, required: true

p
  = f.label :presenter
  br
  = f.text_field :presenter

p
  = f.label :start_date, class: "required"
  br
  = f.date_select :start_date, required: true

p
  = f.label :end_date
  br
  = f.date_select :end_date, { prompt: true }

p
  = f.label :description
  br
  = f.text_area :description

p
  = f.label :website
  br
  = f.text_field :website

p
  = f.label :facebook, "Link to Facebook page"
  br
  = f.text_field :facebook

p
  = f.label :instagram, "Link to Instagram"
  br
  = f.text_field :instagram

p
  = f.label :twitter, "Link to Twitter"
  br
  = f.text_field :twitter

p
  = f.label :youtube, "Link to Youtube channel"
  br
  = f.text_field :youtube

p = f.submit

app/views/events/edit.html.slim
h3
  ' Edit
  =< @event.name

= render 'shared/flash_messages' if !flash.empty?

= form_for @event do |f|
  = render "form", f:f

app/views/events/index.html.slim
= render 'shared/flash_messages' if !flash.empty?

p = link_to "Add New Event", new_event_path

h3 List of Events

table.tablesorter#events-index
  thead
    tr
      th Name
      th Cities
      th Country
      th Start Date
      th.sorter-false End Date
      th.sorter-false Description
      th Last Updated
      th.sorter-false
  tbody
    - @events.each do |e|
      tr
        td = e.name
        td = comma_separated_list(e.venues.cities)
        td = comma_separated_list(e.venues.countries)
        td = e.start_date
        td = e.end_date
        td = e.description
        td = e.updated_at
        td
          = link_to "View", e
          =< link_to "Edit", edit_event_path(e)
          br
          = link_to "Remove", e, :method => :delete, data: {confirm: "Are you sure you want to remove this event?"}, class: "red"

app/views/events/new.html.slim
h3 New Event

= form_for @event do |f|
  = render "form", f:f

app/views/events/show.html.slim
= render 'shared/flash_messages' if !flash.empty?

h3 = @event.name

p
  ' #{@event.start_date.strftime("%b %e, %Y")} to #{@event.end_date.strftime("%b %e, %Y")} |
  =<> comma_separated_list(@event.venues.countries)
  ' | Presented by #{@event.presenter}

p = @event.description

- unless @event.website.blank?
  span
    ' Website:
    =< link_to @event.website, @event.website, target: "blank"
  br
- unless @event.facebook.blank?
  span
    ' Facebook:
    =< link_to @event.facebook, @event.facebook, target: "blank"
  br
- unless @event.instagram.blank?
  span
    ' Instagram:
    =< link_to @event.instagram, @event.instagram, target: "blank"
  br
- unless @event.twitter.blank?
  span
    ' Twitter:
    =< link_to @event.twitter, @event.twitter, target: "blank"
  br
- unless @event.youtube.blank?
  span
    ' Youtube:
    =< link_to @event.youtube, @event.youtube, target: "blank"
  br

p = link_to "Click to edit event details", edit_event_path(@event)

br
br

h4 Associated venues

table.model-list
  - @event.venues.each do |venue|
    tr
      td = link_to venue.name, venue_path(venue)
      td = link_to "Remove from event", delete_venue_from_event_path(:venue_id => venue.id), :method => :post, data: {:confirm => "Are you sure you want to remove this venue association?"}, class: "red"

app/views/events/tablesort.html.slim
.col-menu
  .directory-main
    = link_to root_path, class: "link-latest" do
      .col-header-wrapper
        .col-header-title Directory
    .directory-entries
      .directory-subtitle Country
      - @recent_countries.each do |country|
        .directory-entry.link-country data-country="#{country}" = country

      .directory-subtitle &nbsp;

      .directory-subtitle Type
      .directory-entry.link-type Play
      .directory-entry.link-type Musical
      .directory-entry.link-type Festival
      .directory-entry.link-type Biennial

  .search Search...

  .map-other Map

.col-latest.hidden
  .latest
    .col-header-wrapper
      .col-header-title Latest
    .latest-entries
      - @events.each do |e|
        .latest-entry.link-details data-event-id="#{e.id}"
          .latest-entry-name = e.name
          .latest-entry-city = e.primary_city

.col-cities.hidden
  .cities data-country=""
    .col-header-wrapper
      .col-header-title Country
      .sort-dropdown.collapsed
        .sort-dropdown-title
          = link_to "Sort By...", "", class: "sort-dropdown-toggle"
        .sort-dropdown-collapsible
          = link_to "City A-Z", "", class: "link-sort", :data => { :sort_by => "City", :tablesorter => "[[0,0]]" }
          .sort-dropdown-events.hidden
            = link_to "Title A-Z", "", class: "link-sort", :data => { :sort_by => "Name", :tablesorter => "[[0,0]]" }
            = link_to "Start Date", "", class: "link-sort", :data => { :sort_by => "Start Date", :tablesorter => "[[2,0]]" }
          = link_to "Added: New to Old", "", class: "link-sort", :data => { :sort_by => "Updated At", :tablesorter => "[[3,1]]" }
    table#cities-table.tablesorter
      thead
        tr
          th.sorter-false Country
      tbody
        tr
          td

.col-details.hidden
  .details data-event-id=-1
    .details-title
    .details-entry

app/views/home/dashboard.html.slim
h3 Your Dashboard

p = link_to "View all events", events_path
p = link_to "View all venues", venues_path

app/views/home/directory.html.slim
.col-menu
  .directory-main
    = link_to root_path, class: "link-latest" do
      .col-header-wrapper
        .col-header-title Directory
    .directory-entries
      .directory-subtitle Country
      - @recent_countries.each do |country|
        .directory-entry.link-country data-country="#{country}" = country

  .search Search...

  .modus-other
    = link_to map_path do
      .col-header-title Map

.col-latest.hidden
  .latest
    .col-open-header-wrapper
      .col-header-title Latest
    .latest-entries
      - @events.each do |e|
        .latest-entry.link-details data-event-id="#{e.id}"
          .latest-entry-name = e.name
          .latest-entry-city = e.primary_city

.col-cities.hidden
  .cities data-country=""
    .col-open-header-wrapper
      .col-header-title Country
      .sort-dropdown.collapsed
        .sort-dropdown-title
          = link_to "Sort By...", "", class: "sort-dropdown-toggle"
        .sort-dropdown-collapsible
          = link_to "City A-Z", "", class: "link-sort", :data => { :sort_by => "City", :tablesorter => "[[0,0]]" }
          .sort-dropdown-events.hidden
            = link_to "Title A-Z", "", class: "link-sort", :data => { :sort_by => "Name", :tablesorter => "[[0,0]]" }
            = link_to "Start Date", "", class: "link-sort", :data => { :sort_by => "Start Date", :tablesorter => "[[2,0]]" }
          = link_to "Added: New to Old", "", class: "link-sort", :data => { :sort_by => "Updated At", :tablesorter => "[[3,1]]" }
    table#cities-table.tablesorter
      thead
        tr
          th.sorter-false Country
      tbody
        tr
          td

.col-details.hidden
  .details data-event-id=-1
    .details-title
    .details-entry

app/views/home/map.html.slim
#map-wrapper
  #menu-overlay
    h1 = link_to "Performap", root_path

    .col-menu
      .map-main Map

      .search Search...

      .modus-other
        = link_to root_path do
          .col-header-title Directory

  #desc-overlay
    #col-desc.hidden
      .desc data-event-id=-1
        .desc-title Sample Title
        .desc-entry Sample Entry

  #map

  script[async defer src=google_maps_url data-turbolinks-track="false"]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Performap</title>
    <%= include_gon %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:400,700" %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <div class="container">
      <div id="performap-logo-link">
        <h1><%= link_to "Performap", root_path %></h1>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.slim
#flash-messages
  - flash.each do |key, value|
    = content_tag :div, value, class: "flash #{key}"

app/views/users/new.html.slim
h3 Sign Up

= form_for @user do |f|
  p
    = f.label :name, class: "required"
    = f.text_field :name, required: true

  p
    = f.label :email, class: "required"
    = f.email_field :email, required: true

  p
    = f.label :password, class: "required"
    = f.password_field :password, required: true

  p
    = f.label :password_confirmation, class: "required"
    = f.password_field :password_confirmation, required: true

  = f.submit "Submit"

app/views/venues/_form.html.slim
p
  = f.label :name, class: "required"
  br
  = f.text_field :name, required: true

p In order to change the address of this venue, please update the field "Given address" below.
p
  = f.label :given_address, class: "required"
  br
  = f.text_field :given_address, required: true
br

.warning-box
  p The following fields are automatically filled in and updated using Google Maps geocoding service based on the given address above.
  p We do not recommend directly changing the fields below.

  p
    = f.label :latitude
    br
    = f.text_field :latitude

  p
    = f.label :longitude
    br
    = f.text_field :longitude

  p
    = f.label :formatted_address
    br
    = f.text_field :formatted_address

  p
    = f.label :street_address
    br
    = f.text_field :street_address

  p
    = f.label :city
    br
    = f.text_field :city

  p
    = f.label :state
    br
    = f.text_field :state

  p
    = f.label :country
    br
    = f.text_field :country

p = f.submit

app/views/venues/edit.html.slim
h3
  ' Edit
  =< @venue.name

= render 'shared/flash_messages' if !flash.empty?

= form_for @venue do |f|
  = render "form", f:f

app/views/venues/index.html.slim
h3 List of Venues

table.tablesorter#venues-index
  thead
   tr
     th Name
     th.sorter-false Street Address
     th City
     th State
     th Country
     th Associated Events
     th.sorter-false

  tbody
    - @venues.each do |v|
      tr
        td = v.name
        td = v.street_address
        td = v.city
        td = v.state
        td = v.country
        td = comma_separated_list(v.events.names)
        td
          = link_to "View", venue_path(v)
          =< link_to "Edit", edit_venue_path(v)

app/views/venues/show.html.slim
= render 'shared/flash_messages' if !flash.empty?

h3 = @venue.name

p = @venue.formatted_address

p = link_to "Click to edit venue details", edit_venue_path(@venue)

br
br

h4 Associated events

table.model-list
  - @venue.events.each do |event|
    tr
      td = link_to event.name, event_path(event)
      td = link_to "Remove from venue", delete_event_from_venue_path(:event_id => event.id), :method => :post, data: {:confirm => "Are you sure you want to remove this event association?"}, class: "red"